### ISSUE TITLE
Delete a test doesn't remove test result data

### ISSUE THREAD

**Issue by fkbecker** [AlfrescoBenchmark/alfresco-benchmark#113]
Delete a test: Test und test runs are removed, the events and results not.
Now create a new test and test run with the same names and execute. Engine will reuse the old event results and fail to execute the test.

**Comment by derekhulley** [comment]
It is meant to cascade delete as if the user had manually gone into the test and deleted each run from the UI.  I think there is also an issue if the test is renamed before the whole lot is deleted but that would be a separate issue.

**Comment by derekhulley** [comment]
This is a regression - perhaps from 1.4.
Even when deleting the test run itself, the data is not removed.
In my view, this needs fixing urgently as it's a pain to have all the data lying around.

**Comment by fkbecker** [comment]
This WILL be fixed in 2.1.4 - for it prevents to re-create and run a test run with the same names. 
Having all the data lying around is sure an issue, too.

**Comment by derekhulley** [comment]
Thanks.

**Comment by fkbecker** [comment]
This seems to be a configuration issue. MongoDB 3.2 driver does not support the option "autoConnectRetry" any longer. The clean code uses this parameter and fails to create the mongo client that removes the extra data ... 

However the "clean" parameter in the RestAPI call is never used anyway (so it's always set to true) and I think we should ALWAYS drop those extra data. What do you think about this?

**Comment by derekhulley** [comment]
If we're not going to add an option to the UI to retain the data, then the
API option might as well be removed, too.

**Comment by fkbecker** [comment]
More tests needed. The JUnit tests were a bit unlucky created - they worked because they set all the properties to the values it couldn't fail ^^

**Comment by fkbecker** [comment]
Fixed with 2.1.4
