### ISSUE TITLE
Test run name validation is inconsistent during copy

### ISSUE THREAD

**Issue by derekhulley** [AlfrescoBenchmark/alfresco-benchmark#114]
![test-run-copy](https://cloud.githubusercontent.com/assets/5584103/15160207/85f68e88-16f0-11e6-9b9d-b6b17f2135e6.png)
When creating a test run, numeric-only names are allowed, in keeping with the validation that occurs on the server.
However, when attempting to copy a test run, the validation appears to be the same as that of the test name validation.
* Create a test run 001
* Create a test run 002
* Copy test run 001 and attempt to call it 003

**Comment by fkbecker** [comment]
Thanks for showing me this. 

More issues: create run does not validate at all, edit test run name during edit properties also fails with the same error message.

**Comment by fkbecker** [comment]
Fixed with 2.1.4
