### ISSUE TITLE
Import and export from tests<->test runs

### ISSUE THREAD

**Issue by derekhulley** [AlfrescoBenchmark/alfresco-benchmark#115]
The import/export feature is very useful.
If the user could import and export the json settings from both tests and test runs, then that would be ideal.

The scenario is this:
A sequence of test runs typically starts with a simple run to ensure that everything is working.  If the user keeps the json for that run as a starting point and uses that to create the _test_, then several trial iterations can be quickly run without having to re-import settings for each test run.  This is quite common because the environment frequently displays problems brought out under the initial load conditions: executing 6 small load tests to get things sorted out is not uncommon.

After that has been successful, the user has a test with the required settings for the first basic test and can then import subsequent settings for the more complicated test runs.  This feature is already supported.

**Comment by fkbecker** [comment]
This will be done in a future version - 2.1.4 is mainly a big "bugfix" version that makes the BM framework much better usable. However this feature will be very useful and implemented asap.

**Comment by fkbecker** [comment]
Done with BM Server 2.2.0
