### ISSUE TITLE
Log level too fine

### ISSUE THREAD

**Issue by derekhulley** [AlfrescoBenchmark/alfresco-benchmark#122]
The current log level outputs too much DEBUG information by default, which causes file overflow in production-deployed servers.  An overlay file could be generated for test purposes but the log levels should return to what they were around the 2.0.10 release.

See build BENCHMARK-BMFWK-JOB1/build_logs/BENCHMARK-BMFWK-JOB1-302.log

> build 31-May-2016 11:16:58    11:16:58,266 [        main] [DEBUG] [                  MongoEventService: 337] - 
> build   31-May-2016 11:16:58    Fetched next event (no lock present): 
> build   31-May-2016 11:16:58       Latest scheduled time:  1464689818265
> build   31-May-2016 11:16:58       Driver ID:              null
> build   31-May-2016 11:16:58       Event: Event [id=574d649a8b5c1568a99774f2, name=E-1, sessionId=null, scheduledTime=1464689818199, lockOwner=62f9ed77-116d-40fc-a9c5-85ae82751360, lockTime=1464689818265, data={ "D-0" : 0 , "D-1" : 1 , "D-2" : 2 , "D-3" : 3 , "D-4" : 4 , "D-5" : 5 , "D-6" : 6 , "D-7" : 7 , "D-8" : 8 , "D-9" : 9}, dataInMemory=false, driver=DRIVER-5]

**Comment by fkbecker** [comment]
Thanks for showing me this, it was never intended to set the log level to DEBUG. 

I will add a "check for debug code and settings" section in the release guide. 
There will be a new release in the next few weeks because for the new BM controller application we need same small extensions in the RestAPI anyway.

**Comment by fkbecker** [comment]
Fixed with 2.2.0 (coming soon)
