### ISSUE TITLE
FTP error while doing Data load test

### ISSUE THREAD

**Issue by Yogesh102** [AlfrescoBenchmark/alfresco-benchmark#124]
Team,

I have configured alfresco benchmark server and dataload driver in to my local. 
However, when I am doing data load test I am getting following error. I am doubting that weather FTP server information are correct or not ?

Failed to start test run application 'Dataload1.test6. 
 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testFileService' defined in class path resource [config/spring/test-context.xml]: Invocation of init method failed; nested exception is java.lang.RuntimeException: FTP file listing failed: FtpTestFileService [ftpHost=ftp.mirrorservice.org, ftpPort=21, ftpUsername=anonymous, ftpPassword=*****, ftpPath=/sites/www.linuxfromscratch.org/images]
 at 

Thanks,
Yogesh Prajapati

**Comment by derekhulley** [comment]
Yes, the load driver is failing to contact the location *ftp://ftp.mirrorservice.org/sites/www.linuxfromscratch.org/images/*.
Check that your load driver (i.e. try it out on the machine) is able to access the link above.  You can use a different - possibly private - ftp server as well.
