### ISSUE TITLE
is there any way to stop the test once it is started ?

### ISSUE THREAD

**Issue by Yogesh102** [AlfrescoBenchmark/alfresco-benchmark#125]

**Comment by fkbecker** [comment]
Sure, simply press the stop icon in the details view.

**Comment by Yogesh102** [comment]
Ohh  I got it. Thanks. I did the data load test. I am not sure but I think ftp server which is mentioned in benchmark framework (default)  is not working. I have created local ftp server in my machine and I am using it. But after running test, I do see the 10 sites are created but I am not seeing any files or folders in it except documentlibrary. Is there any configuration we have to do ?

**Comment by derekhulley** [comment]
What happens if you create another test run (straight copy) and start that?

**Comment by Yogesh102** [comment]
I have tried it. I have copied the same test case and run it. But it did not created any folder or files.
Just FYI, I have also enabled smart folders option to true ( I am using alfresco 5.1) , file spoofing to true and also I have increased the file & folders creation parameters. Not sure what is going on. In console I am finding a lot of logs and in UI logs I am not able to find much information. Looks like I have to debug it more.

**Comment by fkbecker** [comment]
If you use file spoofing in Data Load it will not download and create Files and folders from FTP. Please try out with the default configuration and only change the TFP for a first run. Once you have it up and working add more features as needed.

**Comment by Yogesh102** [comment]
No luck. I have made file spoofing false but still it is not creating files and folders. I am debugging it. Just want to know about mongodb schema. I do see around 50 files in mirror.cached.files collection. But it is just document information nothing alfresco information.

**Comment by Yogesh102** [comment]
Do you have any update ? I am still facing the same issue. I am trying to debug the code.
