### ISSUE TITLE
Getting HTTP 404 for  /api/v1/test-defs?activieOnly=true request

### ISSUE THREAD

**Issue by Yogesh102** [AlfrescoBenchmark/alfresco-benchmark#127]
I am using alfresco benchmark 2.1.4 and I have registered the sample driver but I am getting http 404 for test-defs request.

Can anyone help me on this  ?

**Comment by derekhulley** [comment]
Please give a thorough description of the steps you performed to get to where you are.

**Comment by Yogesh102** [comment]
Thanks Derek. I have resolved the issue. Not sure but I was replicating whole benchmark environment setup which I did in my local but I took different version for benchmark server,tomcat version, mongodb etc..
May be that was causing the issue.
