### ISSUE TITLE
CMIS test load control limit ?

### ISSUE THREAD

**Issue by Yogesh102** [AlfrescoBenchmark/alfresco-benchmark#128]
I am performing CMIS test with 2000 cmis session as load control limit.
But in the result it is showing less than 1500. Is there any limit for it ?

**Comment by derekhulley** [comment]
There is no limit.
You should post your settings here - you may need to look at the **Load Control** and make sure that you are giving the test enough time to run to completion.

The number of sessions will be one things that determines how long the test runs.  The other is a hard time cut off under *Load Control*.

**Comment by Yogesh102** [comment]
![localhost-8080-alfresco-benchmark-server-2-1-4-1501522446518](https://user-images.githubusercontent.com/8981260/28789867-1643b0b0-75f5-11e7-810a-8f0d93ae5b88.png)

**Comment by Yogesh102** [comment]
I have attached the settings which you have asked. I have changed the CMIS session delay from 100 to 300. Also, what is the test duration means? Does this mean that it will run the test for defined time only and then it will stop?

**Comment by derekhulley** [comment]
Yes, the Test Duration is a hard stop.
A test can be configured to watch for a number of stop signals and will
always base the duration (and estimate) on whichever comes first.
So, for your settings, I would expect that you would get about 1000
sessions done before the test terminates based on time.

The duration is very useful when you just want to chuck something at a
server for a specific time and do not want to calculate the number of
sessions to create, etc.
It's also good to set it a bit longer than you expect as it will stop a
test that has killed your server, which can lead to backed up http calls,
etc.
