### ISSUE TITLE
server.xml and JMX dump

### ISSUE THREAD

**Issue by hjanjua** [AlfrescoBenchmark/alfresco-benchmark#129]
Is it possible if you can share server.xml and JMX dump of this environment?

**Comment by derekhulley** [comment]
Which environment?

**Comment by hjanjua** [comment]
alfresco nbenchmark environment which was used to billion documents?

**Comment by derekhulley** [comment]
I am not sure what the server.xml and jmx dump would provide, or even which instances of that environment you refer to.  Any useful information has been gathered in the scaling document that is available from Alfresco.
