### ISSUE TITLE
Property editing usability

### ISSUE THREAD

**Issue by derekhulley** [AlfrescoBenchmark/alfresco-benchmark#25]
The use of horizontal screen space leaves little room for wide properties.  On lower resolution displays, the space available to edit the property value is a small fraction of the space available.

**Comment by derekhulley** [comment]
Zooming in using the browser:
![benchmark-025-01](https://cloud.githubusercontent.com/assets/5584103/6215813/d319e2e8-b5fb-11e4-868f-bee77a47c8be.png)

**Comment by fkbecker** [comment]
I can't reproduce this with Chrome (Mac OS X) - but instead the values of a property can be moved over the label - what makes them "un-clickable" ... 
<img width="544" alt="bildschirmfoto 2015-10-06 um 17 02 00" src="https://cloud.githubusercontent.com/assets/6104943/10312553/09b47f64-6c4c-11e5-8bc7-3ee23ebd8d02.png">

**Comment by derekhulley** [comment]
This was an issue when trying to use overhead projectors with low resolutions.
Zooming in now, the editing seems to work fine.
