### ISSUE TITLE
Occasional duplicate property value displayed

### ISSUE THREAD

**Issue by derekhulley** [AlfrescoBenchmark/alfresco-benchmark#29]
![bm-duplicate-property](https://cloud.githubusercontent.com/assets/5584103/5037185/9287eee6-6b7d-11e4-99ff-5f681a3bf231.png)

'false' displayed twice.  This sometimes happens with numeric values as well.
The test is BM Share 5.0.0-SNAPSHOT schema 1.

**Comment by fkbecker** [comment]
To reproduce, use "SignUp" - whenever "Assume Created" in group "Signup Load Parameters" is changed from the default value "false" to "true" and then back to "false" this appears.

**Comment by fkbecker** [comment]
The reason is the "item.value" - if this can be casted to a "boolean" (JavaScript vars don't have a fixed type!) the default value also shows up.
