### ISSUE TITLE
UI must show recent activity logs

### ISSUE THREAD

**Issue by derekhulley** [AlfrescoBenchmark/alfresco-benchmark#32]
Need a view of all recent log activity
 - limited to N results
 - filtered by
  - nothing
  - test (default view on the test screen)
  - test and run (default view on the run summary page)

Manual and auto-refresh options.  For api, use *<bm-server>/api/v1/logs* as per *readme.txt*.

**Comment by fkbecker** [comment]
Parts of this issue are solved by Paul ... there is a "refreh" button, but the results are sorted only by the level - this leads to a mis-order when refreshing.

**Comment by fkbecker** [comment]
See #60 - displays the last N events. 
Logs can also be refreshed and sorted. Closing this ...
