### ISSUE TITLE
Unable to edit property when the default is an empty string

### ISSUE THREAD

**Issue by derekhulley** [AlfrescoBenchmark/alfresco-benchmark#35]
If a test has a 'string' type property that is an empty string, then the property editor gives the user no way to alter the value.

An example is to run the Alfresco Sign Up test:
<pre>
svn checkout -r 93038 https://svn.alfresco.com/repos/alfresco-enterprise/benchmark/tests/ent-signup/trunk ent-signup
</pre>
The "UserDetails.Groups" value is empty by default and cannot be modified.

A workaround is to set the 'user.groups' property using the a PUT directly to the API:
<pre>
http://<server>:9080/alfresco-benchmark-server/api/v1/tests/<test>props/user.groups
   {
      "version":"0",
      "value":"SITE_ADMINISTRATORS:0.1"
   }
</pre>
and the property will not be editable via the UI.

**Comment by fkbecker** [comment]
The Share test 5.1 also has an empty default value, that is not editable by the UI.

**Comment by fkbecker** [comment]
Boolean values has (Empty) now, too ... the compare to unset default must be changed!
