### ISSUE TITLE
Alfresco/CMIS server connection issue: test can't be stopped

### ISSUE THREAD

**Issue by fkbecker** [AlfrescoBenchmark/alfresco-benchmark#75]
Share Test: lots of exceptions in log, but NO message in the UI - neither events nor logs
Sign-Up Test: No exceptions in log, but also no UI - and it is not possible to stop the test 
Desktop Sync: Test stops - display in Events available, because this test has a "validation event step"
Data load: can be started due to invalid credentials no feedback in the UI, stop not possible
Track document creation: can be  started but never stopped if CMIS connection fails, no display in UI, too

**Comment by fkbecker** [comment]
With server 2.1 the test should now stop if CMIS and/or FTP data is incorrect.

**Comment by paulbrodner** [comment]
nice one Frank! :+1:
