### ISSUE TITLE
Add support for exporting/importing test settings

### ISSUE THREAD

**Issue by paulbrodner** [AlfrescoBenchmark/alfresco-benchmark#95]
Add UI ability to export/import test configuration settings.
Useful if we want to use same settings, on multiple machines.

**Comment by fkbecker** [comment]
Properties of run can be exported in the summary page and the test overview page. 
Import is possible for run only on the test overview page. 

Note: the exported file is JSON - it can be modified manual. If you need to change passwords just remove the "cipher" field and store the password unencrypted. Support for encryption of passwords will be delivered in further versions.
